SELECT CAR_ID,
    CASE
        WHEN CAR_ID IN 
                (SELECT DISTINCT(C.CAR_ID)
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
                WHERE C.START_DATE <= '2022-10-16' AND '2022-10-16' <= C.END_DATE)
            THEN '대여중' ELSE '대여 가능' END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC

