SELECT 'sugar_based' AS INGREDIENT_TYPE, SUM(TOTAL_ORDER)
FROM FIRST_HALF
WHERE FLAVOR IN (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'sugar_based'
)

UNION

SELECT 'fruit_based' AS INGREDIENT_TYPE, SUM(TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF
WHERE FLAVOR IN (
    SELECT FLAVOR
    FROM ICECREAM_INFO
    WHERE INGREDIENT_TYPE = 'fruit_based'
)
# ORDER BY TOTAL_ORDER